name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 11]
        exclude:
          - os: windows-latest
            java: 8
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - name: Test
        run: sbt +test
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: ./bin/scalafmt --check
      - run: sbt scalafixCheckAll
